export const apartments = [
  {
    naziv: "S-1",
    katText: "prizemlje",
    kat: 0,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E0.S-1.1",
        naziv: "Hodnik",
        povrsina: 3.7,
        obloga: "Parket",
        obracunska: 3.7,
      },
      {
        broj: "E0.S-1.2",
        naziv: "Kuhinja",
        povrsina: 7.1,
        obloga: "Parket",
        obracunska: 7.1,
      },
      {
        broj: "E0.S-1.3",
        naziv: "Spremište",
        povrsina: 2.8,
        obloga: "Parket",
        obracunska: 2.8,
      },
      {
        broj: "E0.S-1.4",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 26.8,
        obloga: "Parket",
        obracunska: 26.8,
      },
      {
        broj: "E0.S-1.5",
        naziv: "Kupaonica",
        povrsina: 4.5,
        obloga: "Ker.pl.",
        obracunska: 4.5,
      },
      {
        broj: "E0.S-1.6",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E0.S-1.7",
        naziv: "Loggia",
        povrsina: 7.6,
        obloga: "Ker.pl.",
        obracunska: 5.7,
      },
    ],
  },
  {
    naziv: "S-2",
    katText: "prizemlje",
    kat: 0,
    sobe: 2.5,
    sold: true,
    prostorije: [
      {
        broj: "E0.S-2.1",
        naziv: "Hodnik",
        povrsina: 2.9,
        obloga: "Parket",
        obracunska: 2.9,
      },
      {
        broj: "E0.S-2.2",
        naziv: "Spremište",
        povrsina: 1.8,
        obloga: "Parket",
        obracunska: 1.8,
      },
      {
        broj: "E0.S-2.3",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E0.S-2.4",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.6,
        obloga: "Parket",
        obracunska: 17.6,
      },
      {
        broj: "E0.S-2.5",
        naziv: "Spavaća soba",
        povrsina: 12.0,
        obloga: "Parket",
        obracunska: 12.0,
      },
      {
        broj: "E0.S-2.6",
        naziv: "Hodnik",
        povrsina: 5.6,
        obloga: "Parket",
        obracunska: 5.6,
      },
      {
        broj: "E0.S-2.7",
        naziv: "Kupaonica",
        povrsina: 5.2,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
      {
        broj: "E0.S-2.8",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E0.S-2.9",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.5,
      },
    ],
  },
  {
    naziv: "S-3",
    katText: "prizemlje",
    kat: 0,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E0.S-3.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E0.S-3.2",
        naziv: "Kupaonica",
        povrsina: 5.2,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
      {
        broj: "E0.S-3.3",
        naziv: "Spavaća soba",
        povrsina: 13.1,
        obloga: "Parket",
        obracunska: 13.1,
      },
      {
        broj: "E0.S-3.4",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.9,
        obloga: "Parket",
        obracunska: 19.9,
      },
      {
        broj: "E0.S-3.5",
        naziv: "Kuhinja",
        povrsina: 6.0,
        obloga: "Parket",
        obracunska: 6.0,
      },
      {
        broj: "E0.S-3.6",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E0.S-3.7",
        naziv: "Loggia",
        povrsina: 4.9,
        obloga: "Ker.pl.",
        obracunska: 3.7,
      },
    ],
  },
  {
    naziv: "S-4",
    katText: "1. kat",
    kat: 1,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E1.S-4.1",
        naziv: "Kupaonica",
        povrsina: 5.0,
        obloga: "Ker.pl.",
        obracunska: 5.0,
      },
      {
        broj: "E1.S-4.2",
        naziv: "Hodnik",
        povrsina: 5.2,
        obloga: "Parket",
        obracunska: 5.2,
      },
      {
        broj: "E1.S-4.3",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E1.S-4.4",
        naziv: "Spremište",
        povrsina: 1.8,
        obloga: "Parket",
        obracunska: 1.8,
      },
      {
        broj: "E1.S-4.5",
        naziv: "Hodnik",
        povrsina: 5.4,
        obloga: "Parket",
        obracunska: 5.4,
      },
      {
        broj: "E1.S-4.6",
        naziv: "Spavaća soba",
        povrsina: 11.2,
        obloga: "Parket",
        obracunska: 11.2,
      },
      {
        broj: "E1.S-4.7",
        naziv: "Kuhinja",
        povrsina: 5.6,
        obloga: "Parket",
        obracunska: 5.6,
      },
      {
        broj: "E1.S-4.8",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.3,
        obloga: "Parket",
        obracunska: 17.3,
      },
      {
        broj: "E1.S-4.9",
        naziv: "Loggia",
        povrsina: 6.6,
        obloga: "Ker.pl.",
        obracunska: 4.9,
      },
    ],
  },
  {
    naziv: "S-5",
    katText: "1. kat",
    kat: 1,
    sobe: 1.5,
    sold: true,
    prostorije: [
      {
        broj: "E1.S-5.1",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E1.S-5.2",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 18.9,
        obloga: "Parket",
        obracunska: 18.9,
      },
      {
        broj: "E1.S-5.3",
        naziv: "Kupaonica",
        povrsina: 4.4,
        obloga: "Ker.pl.",
        obracunska: 4.4,
      },
      {
        broj: "E1.S-5.4",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E1.S-5.5",
        naziv: "Hodnik",
        povrsina: 3.7,
        obloga: "Parket",
        obracunska: 3.7,
      },
      {
        broj: "E1.S-5.6",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.5,
      },
    ],
  },
  {
    naziv: "S-6",
    katText: "1. kat",
    kat: 1,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E1.S-6.1",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.6,
        obloga: "Parket",
        obracunska: 17.6,
      },
      {
        broj: "E1.S-6.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E1.S-6.3",
        naziv: "Spremište",
        povrsina: 1.7,
        obloga: "Parket",
        obracunska: 1.7,
      },
      {
        broj: "E1.S-6.4",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E1.S-6.5",
        naziv: "Spavaća soba",
        povrsina: 12.6,
        obloga: "Parket",
        obracunska: 12.6,
      },
      {
        broj: "E1.S-6.6",
        naziv: "Hodnik",
        povrsina: 5,
        obloga: "Parket",
        obracunska: 5,
      },
      {
        broj: "E1.S-6.7",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E1.S-6.8",
        naziv: "Hodnik",
        povrsina: 2.9,
        obloga: "Parket",
        obracunska: 2.9,
      },
      {
        broj: "E1.S-6.9",
        naziv: "Loggia",
        povrsina: 6.6,
        obloga: "Ker.pl.",
        obracunska: 4.9,
      },
    ],
  },
  {
    naziv: "S-7",
    katText: "1. kat",
    kat: 1,
    sobe: 1.5,
    sold: true,
    prostorije: [
      {
        broj: "E1.S-7.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E1.S-7.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E1.S-7.3",
        naziv: "Spavaća soba",
        povrsina: 13.1,
        obloga: "Parket",
        obracunska: 13.1,
      },
      {
        broj: "E1.S-7.4",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.9,
        obloga: "Parket",
        obracunska: 19.9,
      },
      {
        broj: "E1.S-7.5",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E1.S-7.6",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E1.S-7.7",
        naziv: "Loggia",
        povrsina: 4.6,
        obloga: "Ker.pl.",
        obracunska: 3.4,
      },
    ],
  },
  {
    naziv: "S-8",
    katText: "1. kat",
    kat: 1,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E1.S-8.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obloga: "Parket",
        obracunska: 9.8,
      },
      {
        broj: "E1.S-8.2",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obloga: "Parket",
        obracunska: 5.9,
      },
      {
        broj: "E1.S-8.3",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obloga: "Parket",
        obracunska: 23.4,
      },
      {
        broj: "E1.S-8.4",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obloga: "Ker.pl.",
        obracunska: 4.8,
      },
      {
        broj: "E1.S-8.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obloga: "Parket",
        obracunska: 12.8,
      },
      {
        broj: "E1.S-8.6",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E1.S-8.7",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E1.S-8.8",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.4,
      },
    ],
  },
  {
    naziv: "S-9",
    katText: "1. kat",
    kat: 1,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E1.S-9.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obloga: "Parket",
        obracunska: 9.8,
      },
      {
        broj: "E1.S-9.2",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obloga: "Parket",
        obracunska: 5.9,
      },
      {
        broj: "E1.S-9.3",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obloga: "Parket",
        obracunska: 23.4,
      },
      {
        broj: "E1.S-9.4",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obloga: "Ker.pl.",
        obracunska: 4.8,
      },
      {
        broj: "E1.S-9.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obloga: "Parket",
        obracunska: 12.8,
      },
      {
        broj: "E1.S-9.6",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E1.S-9.7",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E1.S-9.8",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.4,
      },
    ],
  },
  {
    naziv: "S-10",
    katText: "1. kat",
    kat: 1,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E1.S-10.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E1.S-10.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E1.S-10.3",
        naziv: "Spavaća soba",
        povrsina: 13,
        obloga: "Parket",
        obracunska: 13,
      },
      {
        broj: "E1.S-10.4",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.5,
        obloga: "Parket",
        obracunska: 19.5,
      },
      {
        broj: "E1.S-10.5",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E1.S-10.6",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E1.S-10.7",
        naziv: "Loggia",
        povrsina: 4.6,
        obloga: "Ker.pl.",
        obracunska: 3.4,
      },
    ],
  },
  {
    naziv: "S-11",
    katText: "2. kat",
    kat: 2,
    sobe: 2.5,
    sold: true,
    prostorije: [
      {
        broj: "E2.S-11.1",
        naziv: "Hodnik",
        povrsina: 5.4,
        obloga: "Parket",
        obracunska: 5.4,
      },
      {
        broj: "E2.S-11.2",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.3,
        obloga: "Parket",
        obracunska: 17.3,
      },
      {
        broj: "E2.S-11.3",
        naziv: "Kuhinja",
        povrsina: 5.6,
        obloga: "Parket",
        obracunska: 5.6,
      },
      {
        broj: "E2.S-11.4",
        naziv: "Spremište",
        povrsina: 1.8,
        obloga: "Parket",
        obracunska: 1.8,
      },
      {
        broj: "E2.S-11.5",
        naziv: "Hodnik",
        povrsina: 5.2,
        obloga: "Parket",
        obracunska: 5.2,
      },
      {
        broj: "E2.S-11.6",
        naziv: "Kupaonica",
        povrsina: 5,
        obloga: "Ker.pl.",
        obracunska: 5,
      },
      {
        broj: "E2.S-11.7",
        naziv: "Spavaća soba",
        povrsina: 11.2,
        obloga: "Parket",
        obracunska: 11.2,
      },
      {
        broj: "E2.S-11.8",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E2.S-11.9",
        naziv: "Loggia",
        povrsina: 7,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
    ],
  },
  {
    naziv: "S-12",
    katText: "2. kat",
    kat: 2,
    sobe: 1.5,
    sold: true,
    prostorije: [
      {
        broj: "E2.S-12.1",
        naziv: "Hodnik",
        povrsina: 3.7,
        obloga: "Parket",
        obracunska: 3.7,
      },
      {
        broj: "E2.S-12.2",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E2.S-12.3",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 18.9,
        obloga: "Parket",
        obracunska: 18.9,
      },
      {
        broj: "E2.S-12.4",
        naziv: "Kupaonica",
        povrsina: 4.5,
        obloga: "Ker.pl.",
        obracunska: 4.5,
      },
      {
        broj: "E2.S-12.5",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E2.S-12.6",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.5,
      },
    ],
  },
  {
    naziv: "S-13",
    katText: "2. kat",
    kat: 2,
    sobe: 2.5,
    sold: true,
    prostorije: [
      {
        broj: "E2.S-13.1",
        naziv: "Hodnik",
        povrsina: 2.9,
        obloga: "Parket",
        obracunska: 2.9,
      },
      {
        broj: "E2.S-13.2",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.5,
        obloga: "Parket",
        obracunska: 17.5,
      },
      {
        broj: "E2.S-13.3",
        naziv: "Spremište",
        povrsina: 1.7,
        obloga: "Parket",
        obracunska: 1.7,
      },
      {
        broj: "E2.S-13.4",
        naziv: "Kuhinja",
        povrsina: 5.4,
        obloga: "Parket",
        obracunska: 5.4,
      },
      {
        broj: "E2.S-13.5",
        naziv: "Hodnik",
        povrsina: 5,
        obloga: "Parket",
        obracunska: 5,
      },
      {
        broj: "E2.S-13.6",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E2.S-13.7",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E2.S-13.8",
        naziv: "Spavaća soba",
        povrsina: 12.6,
        obloga: "Parket",
        obracunska: 12.6,
      },
      {
        broj: "E2.S-13.9",
        naziv: "Loggia",
        povrsina: 7,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
    ],
  },
  {
    naziv: "S-14",
    katText: "2. kat",
    kat: 2,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E2.S-14.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E2.S-14.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E2.S-14.3",
        naziv: "Spavaća soba",
        povrsina: 13.1,
        obloga: "Parket",
        obracunska: 13.1,
      },
      {
        broj: "E2.S-14.4",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E2.S-14.5",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E2.S-14.6",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.9,
        obloga: "Parket",
        obracunska: 19.9,
      },
      {
        broj: "E2.S-14.7",
        naziv: "Loggia",
        povrsina: 4.7,
        obloga: "Ker.pl.",
        obracunska: 3.5,
      },
    ],
  },
  {
    naziv: "S-15",
    katText: "2. kat",
    kat: 2,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E2.S-15.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obloga: "Parket",
        obracunska: 9.8,
      },
      {
        broj: "E2.S-15.2",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obloga: "Ker.pl.",
        obracunska: 4.8,
      },
      {
        broj: "E2.S-15.3",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E2.S-15.4",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E2.S-15.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obloga: "Parket",
        obracunska: 12.8,
      },
      {
        broj: "E2.S-15.6",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obloga: "Parket",
        obracunska: 5.9,
      },
      {
        broj: "E2.S-15.7",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obloga: "Parket",
        obracunska: 23.4,
      },
      {
        broj: "E2.S-15.8",
        naziv: "Loggia",
        povrsina: 7.5,
        obloga: "Ker.pl.",
        obracunska: 5.6,
      },
    ],
  },
  {
    naziv: "S-16",
    katText: "2. kat",
    kat: 2,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E2.S-16.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obloga: "Parket",
        obracunska: 9.8,
      },
      {
        broj: "E2.S-16.2",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obloga: "Ker.pl.",
        obracunska: 4.8,
      },
      {
        broj: "E2.S-16.3",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E2.S-16.4",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E2.S-16.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obloga: "Parket",
        obracunska: 12.8,
      },
      {
        broj: "E2.S-16.6",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obloga: "Parket",
        obracunska: 5.9,
      },
      {
        broj: "E2.S-16.7",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obloga: "Parket",
        obracunska: 23.4,
      },
      {
        broj: "E2.S-16.8",
        naziv: "Loggia",
        povrsina: 7.5,
        obloga: "Ker.pl.",
        obracunska: 5.6,
      },
    ],
  },
  {
    naziv: "S-17",
    katText: "2. kat",
    kat: 2,
    sobe: 1.5,
    sold: true,
    prostorije: [
      {
        broj: "E2.S-17.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E2.S-17.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E2.S-17.3",
        naziv: "Spavaća soba",
        povrsina: 13,
        obloga: "Parket",
        obracunska: 13,
      },
      {
        broj: "E2.S-17.4",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E2.S-17.5",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E2.S-17.6",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.5,
        obloga: "Parket",
        obracunska: 19.5,
      },
      {
        broj: "E2.S-17.7",
        naziv: "Loggia",
        povrsina: 4.7,
        obloga: "Ker.pl.",
        obracunska: 3.5,
      },
    ],
  },
  {
    naziv: "S-18",
    katText: "3. kat",
    kat: 3,
    sobe: 2.5,
    sold: true,
    prostorije: [
      {
        broj: "E3.S-18.1",
        naziv: "Hodnik",
        povrsina: 5.4,
        obloga: "Parket",
        obracunska: 5.4,
      },
      {
        broj: "E3.S-18.2",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.3,
        obloga: "Parket",
        obracunska: 17.3,
      },
      {
        broj: "E3.S-18.3",
        naziv: "Kuhinja",
        povrsina: 5.6,
        obloga: "Parket",
        obracunska: 5.6,
      },
      {
        broj: "E3.S-18.4",
        naziv: "Spremište",
        povrsina: 1.8,
        obloga: "Parket",
        obracunska: 1.8,
      },
      {
        broj: "E3.S-18.5",
        naziv: "Kupaonica",
        povrsina: 5,
        obloga: "Ker.pl.",
        obracunska: 5,
      },
      {
        broj: "E3.S-18.6",
        naziv: "Hodnik",
        povrsina: 5.2,
        obloga: "Parket",
        obracunska: 5.2,
      },
      {
        broj: "E3.S-18.7",
        naziv: "Spavaća soba",
        povrsina: 11.2,
        obloga: "Parket",
        obracunska: 11.2,
      },
      {
        broj: "E3.S-18.8",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E3.S-18.9",
        naziv: "Loggia",
        povrsina: 7,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
    ],
  },
  {
    naziv: "S-19",
    katText: "3. kat",
    kat: 3,
    sobe: 1.5,
    sold: true,
    prostorije: [
      {
        broj: "E3.S-19.1",
        naziv: "Hodnik",
        povrsina: 3.7,
        obloga: "Parket",
        obracunska: 3.7,
      },
      {
        broj: "E3.S-19.2",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E3.S-19.3",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 18.8,
        obloga: "Parket",
        obracunska: 18.8,
      },
      {
        broj: "E3.S-19.4",
        naziv: "Kupaonica",
        povrsina: 4.4,
        obloga: "Ker.pl.",
        obracunska: 4.4,
      },
      {
        broj: "E3.S-19.5",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E3.S-19.6",
        naziv: "Loggia",
        povrsina: 7.3,
        obloga: "Ker.pl.",
        obracunska: 5.5,
      },
    ],
  },
  {
    naziv: "S-20",
    katText: "3. kat",
    kat: 3,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E3.S-20.1",
        naziv: "Hodnik",
        povrsina: 2.9,
        obloga: "Parket",
        obracunska: 2.9,
      },
      {
        broj: "E3.S-20.2",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 17.6,
        obloga: "Parket",
        obracunska: 17.6,
      },
      {
        broj: "E3.S-20.3",
        naziv: "Kuhinja",
        povrsina: 5.3,
        obloga: "Parket",
        obracunska: 5.3,
      },
      {
        broj: "E3.S-20.4",
        naziv: "Spremište",
        povrsina: 1.7,
        obloga: "Parket",
        obracunska: 1.7,
      },
      {
        broj: "E3.S-20.5",
        naziv: "Hodnik",
        povrsina: 5,
        obloga: "Parket",
        obracunska: 5,
      },
      {
        broj: "E3.S-20.6",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E3.S-20.7",
        naziv: "Spavaća soba",
        povrsina: 11.1,
        obloga: "Parket",
        obracunska: 11.1,
      },
      {
        broj: "E3.S-20.8",
        naziv: "Spavaća soba",
        povrsina: 12.6,
        obloga: "Parket",
        obracunska: 12.6,
      },
      {
        broj: "E3.S-20.9",
        naziv: "Loggia",
        povrsina: 7,
        obloga: "Ker.pl.",
        obracunska: 5.2,
      },
    ],
  },
  {
    naziv: "S-21",
    katText: "3. kat",
    kat: 3,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E3.S-21.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E3.S-21.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E3.S-21.3",
        naziv: "Spavaća soba",
        povrsina: 13.1,
        obloga: "Parket",
        obracunska: 13.1,
      },
      {
        broj: "E3.S-21.4",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E3.S-21.5",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E3.S-21.6",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.9,
        obloga: "Parket",
        obracunska: 19.9,
      },
      {
        broj: "E3.S-21.7",
        naziv: "Loggia",
        povrsina: 4.7,
        obloga: "Ker.pl.",
        obracunska: 3.5,
      },
    ],
  },
  {
    naziv: "S-22",
    katText: "3. kat",
    kat: 3,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E3.S-22.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obloga: "Parket",
        obracunska: 9.8,
      },
      {
        broj: "E3.S-22.2",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obloga: "Ker.pl.",
        obracunska: 4.8,
      },
      {
        broj: "E3.S-22.3",
        naziv: "Spremište",
        povrsina: 2.1,
        obloga: "Parket",
        obracunska: 2.1,
      },
      {
        broj: "E3.S-22.4",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obloga: "Parket",
        obracunska: 12.4,
      },
      {
        broj: "E3.S-22.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obloga: "Parket",
        obracunska: 12.8,
      },
      {
        broj: "E3.S-22.6",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obloga: "Parket",
        obracunska: 5.9,
      },
      {
        broj: "E3.S-22.7",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obloga: "Parket",
        obracunska: 23.4,
      },
      {
        broj: "E3.S-22.8",
        naziv: "Loggia",
        povrsina: 7.5,
        obloga: "Ker.pl.",
        obracunska: 5.6,
      },
    ],
  },
  {
    naziv: "S-23",
    katText: "3. kat",
    kat: 3,
    sobe: 2.5,
    prostorije: [
      {
        broj: "E3.S-23.1",
        naziv: "Hodnik",
        povrsina: 9.8,
        obracunska: 9.8,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.2",
        naziv: "Kupaonica",
        povrsina: 4.8,
        obracunska: 4.8,
        obloga: "Ker.pl",
      },
      {
        broj: "E3.S-23.3",
        naziv: "Spremište",
        povrsina: 2.1,
        obracunska: 2.1,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.4",
        naziv: "Spavaća soba",
        povrsina: 12.4,
        obracunska: 12.4,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.5",
        naziv: "Spavaća soba",
        povrsina: 12.8,
        obracunska: 12.8,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.6",
        naziv: "Kuhinja",
        povrsina: 5.9,
        obracunska: 5.9,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.7",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 23.4,
        obracunska: 23.4,
        obloga: "Parket",
      },
      {
        broj: "E3.S-23.8",
        naziv: "Loggia",
        povrsina: 7.5,
        obracunska: 5.6,
        obloga: "Ker.pl.",
      },
    ],
  },
  {
    naziv: "S-24",
    katText: "3. kat",
    kat: 3,
    sobe: 1.5,
    prostorije: [
      {
        broj: "E3.S-24.1",
        naziv: "Hodnik",
        povrsina: 5.7,
        obloga: "Parket",
        obracunska: 5.7,
      },
      {
        broj: "E3.S-24.2",
        naziv: "Kupaonica",
        povrsina: 5.1,
        obloga: "Ker.pl.",
        obracunska: 5.1,
      },
      {
        broj: "E3.S-24.3",
        naziv: "Spavaća soba",
        povrsina: 13,
        obloga: "Parket",
        obracunska: 13,
      },
      {
        broj: "E3.S-24.4",
        naziv: "Spremište",
        povrsina: 2,
        obloga: "Parket",
        obracunska: 2,
      },
      {
        broj: "E3.S-24.5",
        naziv: "Kuhinja",
        povrsina: 6,
        obloga: "Parket",
        obracunska: 6,
      },
      {
        broj: "E3.S-24.6",
        naziv: "Dnevni boravak i blagovanje",
        povrsina: 19.5,
        obloga: "Parket",
        obracunska: 19.5,
      },
      {
        broj: "E3.S-24.7",
        naziv: "Loggia",
        povrsina: 4.7,
        obloga: "Ker.pl.",
        obracunska: 3.5,
      },
    ],
  },
];

apartments.forEach((apartment) => {
  const sum = (key) =>
    apartment.prostorije.reduce((acc, curr) => acc + curr[key], 0).toFixed(1);
  apartment.povrsina = sum("povrsina");
  apartment.obracunska = sum("obracunska");
});

export function getApartment(apartmentName) {
  if (!apartmentName) return null;
  return apartments.find(
    (apartment) => apartment.naziv === apartmentName.toUpperCase()
  );
}
