import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { classnames } from "@/lib/util";
import { FrankopanskaImageGallery } from "@/components/image-gallery/ImageGallery";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.main}>
        <section className={styles.banner}>
          <div className={styles.bannerBackground} />
          <div className={styles.bannerContent}>
            <h1 className={styles.bannerTitle}>UGT Invest</h1>
            <p className={styles.bannerDescription}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <Link
              href="/gradnja-stanova-bjelovar"
              className={classnames("btn-primary", styles.bannerButton)}
            >
              Saznajte više
            </Link>
          </div>
        </section>
        <section className={styles.about}>
          <div
            className={classnames(
              "container",
              "container-wide",
              styles.aboutContainer
            )}
          >
            <h2 className={styles.aboutTitle}>Tko smo?</h2>
            <p className={styles.aboutDescription}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </div>
        </section>
        <section className={classnames(styles.about, styles.frankopanska)}>
          <div
            className={classnames(
              "container",
              "container-wide",
              styles.aboutContainer
            )}
          >
            <h2
              className={classnames(
                styles.aboutTitle,
                styles.frankopanskaTitle
              )}
            >
              Projekt Frankopanska
            </h2>
            <p className={styles.aboutDescription}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </div>
          <div className={styles.gallery}>
            <FrankopanskaImageGallery />
          </div>
          <div className={styles.btnContainer}>
            <Link
              href="/projekt-frankopanska"
              className={classnames("btn-primary", styles.bannerButton)}
            >
              Saznajte više
            </Link>
          </div>
        </section>
      </div>
    </>
  );
}
